

run_test: compile_test
	./elevator_algorithm_test.out

compile_test: elevator_algorithm_test.c
	gcc -o elevator_algorithm_test.out ../elevator_algorithm.c ../../order_queue/orderQueue.c elevator_algorithm_test.c
